# Generated by Django 5.0.6 on 2024-05-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('father_name', models.CharField(max_length=100)),
                ('student_class', models.CharField(max_length=20)),
                ('percentage_10th', models.FloatField()),
                ('marksheet_pdf', models.FileField(upload_to='marksheets/')),
                ('address', models.TextField()),
            ],
        ),
    ]
